export interface movement_categorys {
  title: string;
  movements: string[];
}

export const exserciseList: movement_categorys[] = [
  {
    title: "CHEST",
    movements: [
      "Barbell bench press",
      "Cable chest flyes",
      "Cable chest press with neutral grip",
      "Cable crossovers",
      "Chest dips on parallel bars",
      "Chest flyes",
      "Chest press machine",
      "Close-grip bench press",
      "Decline bench press",
      "Decline dumbbell flyes",
      "Decline dumbbell press",
      "Dips",
      "Dumbbell bench press",
      "Dumbbell pullover",
      "Feet-elevated push-ups",
      "Floor press",
      "Incline bench press",
      "Incline dumbbell flyes",
      "Incline dumbbell press",
      "Landmine press",
      "Machine chest press with neutral grip",
      "Medicine ball chest passes",
      "One-arm cable chest press",
      "One-arm dumbbell bench press",
      "Pec deck machine",
      "Plyometric chest press with medicine ball",
      "Plyometric push-ups",
      "Push-up with hand release",
      "Push-ups with feet on stability ball",
      "Push-ups",
      "Resistance band chest flyes",
      "Resistance band chest press",
      "Reverse-grip bench press",
      "Smith machine bench press",
      "Spiderman push-ups",
      "Stability ball push-ups",
      "Standing cable chest press",
      "Swiss ball dumbbell flyes",
      "Swiss ball dumbbell press",
      "Wide-grip bench press",
    ],
  },
  {
    title: "SHOULDERS",
    movements: [
      "Arnold press",
      "Barbell high pull",
      "Barbell overhead press",
      "Barbell push press",
      "Barbell shrugs",
      "Bent-over lateral raises",
      "Cable face pull with external rotation",
      "Cable lateral raises",
      "Dumbbell Arnold press on stability ball",
      "Dumbbell Cuban press",
      "Dumbbell armpit row",
      "Dumbbell lateral raises with a twist",
      "Dumbbell overhead press",
      "Dumbbell shrugs",
      "Face pulls",
      "Farmers walk",
      "Front raise machine",
      "Front raises",
      "Handstand push-ups",
      "Incline dumbbell press",
      "Kettlebell press",
      "Landmine 180s",
      "Landmine press",
      "Lateral raise machine",
      "Lateral raises",
      "Machine shoulder press",
      "Plate front raises",
      "Plate overhead press",
      "Plate raises",
      "Push press",
      "Reverse flyes",
      "Reverse grip barbell press",
      "Seated dumbbell press",
      "Single-arm cable front raise",
      "Single-arm cable lateral raise",
      "Single-arm cable rear delt fly",
      "Single-arm kettlebell press",
      "Smith machine overhead press",
      "Upright rows",
      "Z press",
    ],
  },
  {
    title: "BICEPS",
    movements: [
      "Bodyweight bicep curls",
      "Cable curls",
      "Cable hammer curls",
      "Cable rope curls",
      "Cable rope hammer curls",
      "Close-grip chin-ups",
      "Concentration curls",
      "Cross-body hammer curls",
      "Decline hammer curls",
      "Drag curls",
      "Dumbbell preacher curls",
      "EZ bar curls",
      "EZ bar reverse curls",
      "Hammer curls",
      "Incline dumbbell curls",
      "Incline hammer curls",
      "Machine curls",
      "One-arm cable curls",
      "One-arm concentration curls",
      "One-arm dumbbell hammer curls",
      "One-arm dumbbell incline curls",
      "Overhand grip cable curls",
      "Preacher curls",
      "Pronated grip barbell curls",
      "Resistance band curls",
      "Reverse curls",
      "Reverse grip cable curls",
      "Seated alternating dumbbell curls",
      "Seated barbell curls",
      "Seated cable curls",
      "Seated incline dumbbell curls",
      "Seated machine curls",
      "Single-arm dumbbell preacher curls",
      "Spider curls",
      "Standing alternating dumbbell curls",
      "Standing rope curls",
      "Standing rope hammer curls",
      "Underhand grip cable curls",
      "Wide-grip barbell curls",
      "Zottman curls",
    ],
  },
  {
    title: "TRICEPS",
    movements: [
      "Banded triceps pushdowns",
      "Bench dips with feet on a stability ball",
      "Cable overhead triceps extensions",
      "Cable rope overhead triceps extensions",
      "Cable rope triceps pushdowns",
      "Cable triceps extensions with a V-bar",
      "Cable triceps kickbacks",
      "Close-grip bench press",
      "Close-grip decline bench press",
      "Close-grip dumbbell floor press",
      "Close-grip dumbbell press",
      "Close-grip push-ups",
      "Diamond push-ups",
      "Dips",
      "Dumbbell triceps kickbacks",
      "EZ bar overhead triceps extensions",
      "EZ bar skull crushers",
      "Incline bench skull crushers",
      "Incline dumbbell triceps extensions",
      "Lying EZ bar triceps extensions",
      "Lying triceps extensions",
      "Machine triceps extensions",
      "One-arm cable triceps extensions",
      "Overhead dumbbell triceps extensions",
      "Overhead triceps cable extensions with a rope attachment",
      "Overhead triceps extensions",
      "Reverse grip triceps pushdowns",
      "Seated dumbbell triceps press",
      "Seated machine triceps dips",
      "Seated overhead dumbbell triceps extensions",
      "Seated triceps press",
      "Single-arm cable triceps pushdowns",
      "Single-arm dumbbell triceps extensions",
      "Skull crushers",
      "Tate press",
      "Triceps dips with a bench",
      "Triceps extensions with a resistance band",
      "Triceps pushdowns with a rope attachment",
      "Triceps pushdowns with a straight bar attachment",
      "Triceps pushdowns",
    ],
  },
  {
    title: "BACK",
    movements: [
      "Assisted pull-ups",
      "Back extensions",
      "Barbell rows",
      "Bent-over barbell rows underhand grip",
      "Bent-over reverse flyes",
      "Bent-over rows",
      "Cable face pulls",
      "Cable straight arm pull-downs",
      "Chest supported dumbbell rows",
      "Chin-ups",
      "Close grip barbell rows",
      "Close grip lat pulldowns",
      "Deadlifts",
      "Dumbbell pullovers",
      "Dumbbell rows",
      "Inverted row with feet elevated",
      "Inverted rows",
      "Kneeling cable pulldowns",
      "Lat pulldowns",
      "Lawnmower rows",
      "One-arm cable rows",
      "Overhand grip cable pulldowns",
      "Prone cobra",
      "Pull-ups",
      "Renegade rows",
      "Reverse grip cable rows",
      "Reverse grip lat pulldowns",
      "Seated cable rows",
      "Seated close grip cable rows",
      "Seated machine rows",
      "Seated wide grip cable rows",
      "Single-arm dumbbell rows",
      "Smith machine rows",
      "Stiff-legged deadlifts",
      "Straight-arm pulldowns",
      "Sumo deadlifts",
      "Supermans",
      "Swiss ball back extensions",
      "T-bar rows",
      "Underhand grip cable pulldowns",
      "Wide grip lat pulldowns",
    ],
  },
  {
    title: "LEGS",
    movements: [
      "Barbell hip thrusts",
      "Barbell lunges",
      "Barbell step-ups",
      "Box jumps",
      "Bulgarian split squats",
      "Calf raises",
      "Curtsy lunges",
      "Deadlifts",
      "Donkey calf raises",
      "Dumbbell step-ups",
      "Front squats",
      "Glute bridges",
      "Goblet squats",
      "Hack squats",
      "Hamstring curls on a stability ball",
      "Jump lunges",
      "Jump rope",
      "Jump squats",
      "Leg abduction machine",
      "Leg adduction machine",
      "Leg curls",
      "Leg extensions",
      "Leg press calf raises",
      "Leg press",
      "Lunges",
      "Pistol squats",
      "Resistance band leg curls",
      "Reverse lunges",
      "Seated calf raises",
      "Seated leg extensions",
      "Side lunges",
      "Single leg calf raises",
      "Single leg press",
      "Single-leg deadlifts",
      "Smith machine calf raises",
      "Smith machine squats",
      "Squats",
      "Standing calf raises",
      "Sumo squats",
      "Zercher squats",
    ],
  },
  {
    title: "GLUTES",
    movements: [
      "Back extensions",
      "Balancing squats",
      "Banded squat walks",
      "Bear crawls",
      "Box jumps",
      "Bulgarian split squats",
      "Cable pull-throughs",
      "Clamshells",
      "Curtsy lunges",
      "Deadlifts",
      "Donkey kicks",
      "Fire hydrants",
      "Flutter kicks",
      "Glute bridges",
      "Hip abduction machine",
      "Hip circles",
      "Hip thrusts",
      "Kettlebell swings",
      "Lateral band walks",
      "Lunges",
      "Mountain climbers",
      "Pistol squats",
      "Plie squats",
      "Plyometric lunges",
      "Resistance band glute bridges",
      "Resistance band kickbacks",
      "Resistance band walks",
      "Reverse hypers",
      "Side-lying leg lifts",
      "Single-leg deadlifts",
      "Single-leg hip thrusts",
      "Skater lunges",
      "Split squats",
      "Sprint drills",
      "Squats",
      "Standing leg lifts",
      "Step-ups",
      "Stiff-legged deadlifts",
      "Sumo deadlifts",
      "Sumo squat pulses",
    ],
  },
  {
    title: "ABS & CORE",
    movements: [
      "Ab wheel rollouts",
      "Bear crawl",
      "Bicycle crunches",
      "Bird dogs",
      "Bosu ball planks",
      "Burpees",
      "Dead bugs",
      "Flutter kicks",
      "Hanging leg raises",
      "Hollow holds",
      "Jackknife sit-ups",
      "Kettlebell swings",
      "Knee tucks",
      "L-sits",
      "Lateral hops",
      "Leg raises",
      "Lunge with twist",
      "Medicine ball slams",
      "Mountain climbers",
      "Pallof press",
      "Pike ups",
      "Plank jacks",
      "Plank with arm raise",
      "Plank",
      "Reverse crunches",
      "Russian leg lifts",
      "Russian twists",
      "Scissor kicks",
      "Side bends",
      "Side plank dips",
      "Side plank",
      "Sit-ups",
      "Spiderman plank",
      "Standing twists",
      "Star plank",
      "The hundred",
      "Toe touches",
      "V-ups",
      "Windshield wipers",
      "Woodchoppers",
    ],
  },
];
