export const hiitdata: string[] = [
  "Agility ladder drills",
  "Air squats",
  "American kettlebell swings",
  "Back rack lunges",
  "Back squats",
  "Bar muscle-ups",
  "Barbell bench presses",
  "Barbell complexes",
  "Barbell lunges",
  "Battle rope ",
  "Bear crawl side shuffles",
  "Bear crawls",
  "Bear crawls",
  "Bench jump overs",
  "Bench jump overs",
  "Bench presses",
  "Box dips",
  "Box jump burpees",
  "Box jumps",
  "Box jumps",
  "Box push-ups",
  "Box step overs",
  "Broad jumps",
  "Bulgarian split squats",
  "Burpee box jumps",
  "Burpees",
  "Burpees",
  "Butt kicks",
  "Chest-to-bar pull-ups",
  "Clean grip deadlifts",
  "Clean grip shrugs",
  "Cone drills",
  "Crab toe touches",
  "Crab walks",
  "Cross jacks",
  "Deadlifts",
  "Dips",
  "Double leg hops",
  "Double unders",
  "Duck walks",
  "Dumbbell bench presses",
  "Dumbbell lunges",
  "Dumbbell push presses",
  "Dumbbell rows",
  "Dumbbell snatches",
  "Dumbbell thrusters",
  "Elevated plyometric lunges",
  "Elliptical machine",
  "Farmer's carries",
  "Farmers carries",
  "Frog jumps",
  "Front rack lunges",
  "Front squats",
  "GHD sit-ups",
  "Good mornings",
  "Handstand push-ups",
  "Handstand walks",
  "Hang cleans",
  "Hang power cleans",
  "Hang snatches",
  "Hang squat cleans",
  "High knees",
  "Hill sprints",
  "Inchworm with spiderman crawl",
  "Inverted rows",
  "Jogging",
  "Jump rope intervals",
  "Jump squats",
  "Jumping jacks",
  "Jumping lateral lunges",
  "Jumping lunges",
  "Jumping lunges",
  "Jumping rope",
  "Kettlebell lunges",
  "Kettlebell swings",
  "Knees to elbows",
  "Lateral jumps",
  "Lateral squat jumps",
  "Lunge jumps",
  "Lunges with barbells",
  "Lunges with dumbbells",
  "Lunges with kettlebells",
  "Lunges with sandbags",
  "Medicine ball cleans",
  "Medicine ball slams",
  "Mountain climbers",
  "Outdoor cycling",
  "Overhead lunges",
  "Overhead squats with barbells",
  "Overhead squats with dumbbells",
  "Overhead squats with kettlebells",
  "Overhead squats",
  "Pike push-ups",
  "Pistol squats",
  "Plank jacks with shoulder taps",
  "Plank jacks",
  "Plank walkouts",
  "Plyometric box jumps",
  "Plyometric lunges",
  "Plyometric push-ups",
  "Pop squats",
  "Power cleans",
  "Power skips",
  "Power snatches",
  "Pull-ups",
  "Push jerks",
  "Push presses",
  "Push-up variations",
  "Push-ups",
  "Reverse lunges",
  "Ring dips",
  "Ring muscle-ups",
  "Ring rows",
  "Rope climbs",
  "Row",
  "Rowing machine",
  "Running",
  "Russian kettlebell swings",
  "Sandbag lunges",
  "Sandbag workouts",
  "Scissor jumps",
  "Shoulder presses",
  "Shuttle runs",
  "Side shuffles",
  "Single arm dumbbell push presses",
  "Single arm dumbbell snatches",
  "Single arm dumbbell thrusters",
  "Single leg hops",
  "Single unders",
  "Skater lunges",
  "Skipping",
  "Sled drags",
  "Sled pulls",
  "Sled pulls",
  "Sled pushes",
  "Sled pushes",
  "Snatch grip deadlifts",
  "Snatch grip shrugs",
  "Spiderman crawls",
  "Split jerks",
  "Sprinting",
  "Sprints with resistance bands",
  "Squat cleans",
  "Squat jumps",
  "Squat jumps",
  "Squat snatches",
  "Stadium stair sprints",
  "Stair climbing",
  "Star jumps",
  "Stationary bike",
  "Step-ups",
  "Suitcase carries",
  "Sumo deadlift high pulls",
  "Swimming",
  "Thrusters",
  "Tire flips",
  "Tire flips",
  "Toes to bar",
  "Treadmill hill sprints",
  "Treadmill intervals",
  "Treadmill running",
  "Tuck jump burpees",
  "Tuck jump push-ups",
  "Tuck jumps",
  "Waiter carries",
  "Walking lunges",
  "Wall balls",
  "Weighted step-ups",
  "Zigzag jumps",
];
