export interface MovementCategory {
  title: string;
  movements: string[];
}

export const yogaPoses: MovementCategory[] = [
  {
    title: "Standing Poses",
    movements: [
      "Mountain Pose",
      "Standing Forward Fold",
      "Warrior I",
      "Warrior II",
      "Tree Pose",
      "Triangle Pose",
      "Extended Hand-To-Big-Toe Pose",
      "Eagle Pose",
      "Garland Pose",
      "Revolved Chair Pose",
      "High Lunge Pose",
      "Warrior III",
    ],
  },
  {
    title: "Seated Poses",
    movements: [
      "Seated Forward Bend",
      "Pigeon Pose",
      "Happy Baby Pose",
      "Easy Pose",
      "Corpse Pose",
      "Thunderbolt Pose",
      "Hero Pose",
      "Lotus Pose",
      "Reclining Hero Pose",
      "Plow Pose",
      "Fish Pose",
      "Half Lord of the Fishes Pose",
      "Seated Wide-Legged Forward Fold",
      "Revolved Side Angle Pose",
      "Revolved Half Moon Pose",
      "Low Lunge Pose",
      "Half Pigeon Pose",
      "Full Pigeon Pose",
      "Extended Side Angle Pose",
      "Cow Face Pose",
      "Half Camel Pose",
      "Intense Side Stretch Pose",
      "Gate Pose",
      "Revolved Triangle Pose",
      "Wide-Legged Seated Forward Bend Twist Pose",
    ],
  },
  {
    title: "Balancing Poses",
    movements: [
      "Half Moon Pose",
      "Revolved Triangle Pose",
      "Extended Hand-To-Big-Toe Pose",
      "Eagle Twist Pose",
      "Reverse Plank Pose",
      "Scale Pose",
      "Shoulder Pressing Pose",
      "Eight-Angle Pose",
      "Eight-Limbed Pose",
      "Bound Half Moon Pose",
      "Baby Grasshopper Pose",
      "Crow Pose with Straight Arms",
      "Firefly Pose",
      "Frog Pose",
      "Grasshopper Pose",
      "Monkey Pose",
    ],
  },
  {
    title: "Inversions",
    movements: [
      "Headstand",
      "Handstand",
      "Wheel Pose",
      "Dolphin Pose",
      "Extended Puppy Pose",
      "Forearm Plank Pose",
      "Dolphin Plank Pose",
      "Shoulderstand",
      "Supported Headstand",
      "Supported Shoulderstand",
      "Legs Up the Wall Pose",
      "Plank Pose",
      "Side Plank",
      "Upward-Facing Dog",
      "Four-Limbed Staff Pose",
      "Upward-Facing Bow Pose",
      "Sphinx Pose",
    ],
  },
  {
    title: "Backbends",
    movements: [
      "Cobra Pose",
      "Fish Pose",
      "Camel Pose",
      "Upward-Facing Dog",
      "Wheel Pose",
      "Bridge Pose",
      "Lizard Pose",
      "Extended Triangle Pose",
      "Revolved Side Angle Pose",
      "Revolved Half Moon Pose",
      "Reverse Warrior Pose",
      "Half Frog Pose",
      "Wild Thing Pose",
      "Half Camel Pose with Quad Stretch",
      "Standing Back Bend Pose",
      "Big Toe Pose",
      "Standing Forward Bend Twist Pose",
      "Lizard Twist Pose",
      "Eight-Limbed Pose",
      "Shoulder Pressing Pose",
    ],
  },
  {
    title: "Twists",
    movements: [
      "Revolved Triangle Pose",
      "Revolved Side Angle Pose",
      "Revolved Chair Pose",
      "Revolved Half Moon Pose",
      "Eagle Twist Pose",
      "Thread the Needle Twist Pose",
      "Happy Baby Twist Pose",
      "Lizard Twist Pose",
      "Seated Twist Pose",
      "Wide-Legged Seated Forward Bend Twist Pose",
    ],
  },
  {
    title: "Balancing Poses",
    movements: [
      "Tree Pose",
      "Eagle Pose",
      "Half Moon Pose",
      "Warrior III",
      "Crow Pose",
      "Side Plank",
      "Dolphin Pose",
      "Scale Pose",
    ],
  },
  {
    title: "Inversions",
    movements: ["Headstand", "Handstand", "Shoulder Pressing Pose"],
  },
  {
    title: "Hip Openers",
    movements: [
      "Pigeon Pose",
      "Happy Baby Pose",
      "Lizard Pose",
      "Half Pigeon Pose",
      "Full Pigeon Pose",
      "Cow Face Pose",
      "Reclined Bound Angle Pose",
    ],
  },
  {
    title: "Arm Balances",
    movements: [
      "Crow Pose",
      "Eight-Angle Pose",
      "Firefly Pose",
      "Grasshopper Pose",
      "Baby Grasshopper Pose",
      "Side Plank",
    ],
  },
  {
    title: "Core Strength",
    movements: [
      "Plank Pose",
      "Side Plank",
      "Boat Pose",
      "Dolphin Plank Pose",
      "Eight-Limbed Pose",
      "Upward-Facing Bow Pose",
      "Forearm Plank Pose",
      "Intense Stretch Pose",
    ],
  },
  {
    title: "Relaxation",
    movements: [
      "Child's Pose",
      "Corpse Pose",
      "Savasana",
      "Extended Puppy Pose",
      "Child’s Pose with Side Stretch",
    ],
  },
  {
    title: "Miscellaneous",
    movements: [
      "Downward-Facing Dog",
      "Cobra Twist Pose",
      "Standing Split Pose",
      "Extended Side Angle Pose",
      "Four-Limbed Staff Pose",
      "Noose Pose",
      "Wild Thing Pose",
      "Reverse Warrior Pose",
      "High Lunge Pose",
      "Extended Hand-To-Big-Toe Pose with Forward Fold",
      "Half Camel Pose with Quad Stretch",
      "Dolphin Pose with Headstand Prep",
      "Dolphin Pose with Forearms on Block",
    ],
  },
];
